"""empty message

Revision ID: 17c3eb1e6a2e
Revises: 2bad15d1fdea
Create Date: 2018-06-14 10:06:15.481051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c3eb1e6a2e'
down_revision = '2bad15d1fdea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('position', sa.String(length=20), nullable=True))
    op.drop_column('result', 'medal_won')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('medal_won', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('result', 'position')
    # ### end Alembic commands ###
