"""empty message

Revision ID: 22eca6dee2ce
Revises: f852f3438e1c
Create Date: 2018-06-01 10:51:04.528439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22eca6dee2ce'
down_revision = 'f852f3438e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadium_sport_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=True),
    sa.Column('sport_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sport_event_id'], ['sport_event.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadium.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('medal_won', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('stadium_sport_event')
    # ### end Alembic commands ###
