"""empty message

Revision ID: 3044d596d02b
Revises: 356855897467
Create Date: 2018-06-14 09:56:19.489636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3044d596d02b'
down_revision = '356855897467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_olympic_year_year', table_name='olympic_year')
    op.drop_table('olympic_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('olympic_year',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('participating_country_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['participating_country_id'], [u'country.id'], name=u'olympic_year_participating_country_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'olympic_year_pkey')
    )
    op.create_index('ix_olympic_year_year', 'olympic_year', ['year'], unique=False)
    # ### end Alembic commands ###
