"""empty message

Revision ID: 357652fef1eb
Revises: 506a8746ca18
Create Date: 2018-06-14 10:38:29.163643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357652fef1eb'
down_revision = '506a8746ca18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('admin', 'username',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.add_column('athlete', sa.Column('olympic_year', sa.DateTime(), nullable=True))
    op.alter_column('athlete', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('athlete', 'email',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.create_index(op.f('ix_athlete_olympic_year'), 'athlete', ['olympic_year'], unique=False)
    op.add_column('country', sa.Column('olympic_year', sa.DateTime(), nullable=True))
    op.alter_column('country', 'climate',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('country', 'continent',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('country', 'country_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('country', 'geolocation',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('country', 'num_of_states',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('country', 'population',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('country', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_country_olympic_year'), 'country', ['olympic_year'], unique=False)
    op.alter_column('result', 'athlete_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('result', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('result', 'sport_event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sport_category', 'sport_category',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.add_column('sport_event', sa.Column('olympic_year', sa.DateTime(), nullable=True))
    op.add_column('sport_event', sa.Column('sport_category_id', sa.Integer(), nullable=False))
    op.alter_column('sport_event', 'sport_event',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.create_index(op.f('ix_sport_event_olympic_year'), 'sport_event', ['olympic_year'], unique=False)
    op.create_foreign_key(None, 'sport_event', 'sport_category', ['sport_category_id'], ['id'])
    op.add_column('stadium', sa.Column('olympic_year', sa.DateTime(), nullable=True))
    op.alter_column('stadium', 'location',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('stadium', 'stadium_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.create_index(op.f('ix_stadium_olympic_year'), 'stadium', ['olympic_year'], unique=False)
    op.alter_column('stadium_sport_event', 'sport_event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stadium_sport_event', 'stadium_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stadium_sport_event', 'stadium_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stadium_sport_event', 'sport_event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_stadium_olympic_year'), table_name='stadium')
    op.alter_column('stadium', 'stadium_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('stadium', 'location',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('stadium', 'olympic_year')
    op.drop_constraint(None, 'sport_event', type_='foreignkey')
    op.drop_index(op.f('ix_sport_event_olympic_year'), table_name='sport_event')
    op.alter_column('sport_event', 'sport_event',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('sport_event', 'sport_category_id')
    op.drop_column('sport_event', 'olympic_year')
    op.alter_column('sport_category', 'sport_category',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('result', 'sport_event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('result', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('result', 'athlete_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_country_olympic_year'), table_name='country')
    op.alter_column('country', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('country', 'population',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('country', 'num_of_states',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('country', 'geolocation',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('country', 'country_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('country', 'continent',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('country', 'climate',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('country', 'olympic_year')
    op.drop_index(op.f('ix_athlete_olympic_year'), table_name='athlete')
    op.alter_column('athlete', 'email',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('athlete', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('athlete', 'olympic_year')
    op.alter_column('admin', 'username',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('admin', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
