"""empty message

Revision ID: 4d5b0d5e8a74
Revises: a5c02df4a12a
Create Date: 2018-06-15 00:38:41.663066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5b0d5e8a74'
down_revision = 'a5c02df4a12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stadium', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stadium', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stadium', type_='foreignkey')
    op.drop_column('stadium', 'country_id')
    # ### end Alembic commands ###
