"""empty message

Revision ID: 4e930f54a967
Revises: 
Create Date: 2018-06-01 10:11:01.846281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e930f54a967'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=30), nullable=True),
    sa.Column('geolocation', sa.String(length=30), nullable=True),
    sa.Column('climate', sa.String(length=20), nullable=True),
    sa.Column('continent', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_country_name'), 'country', ['country_name'], unique=False)
    op.create_table('athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=25), nullable=True),
    sa.Column('surname', sa.String(length=25), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=8), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_email'), 'athlete', ['email'], unique=True)
    op.create_index(op.f('ix_athlete_firstname'), 'athlete', ['firstname'], unique=False)
    op.create_index(op.f('ix_athlete_surname'), 'athlete', ['surname'], unique=False)
    op.drop_table('athlete_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_details',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('surname', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('ath_id', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='athlete_details_pkey'),
    sa.UniqueConstraint('ath_id', name='athlete_details_ath_id_key'),
    sa.UniqueConstraint('email', name='athlete_details_email_key')
    )
    op.drop_index(op.f('ix_athlete_surname'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_firstname'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_email'), table_name='athlete')
    op.drop_table('athlete')
    op.drop_index(op.f('ix_country_country_name'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
