"""empty message

Revision ID: 506a8746ca18
Revises: 5202b9f66f08
Create Date: 2018-06-14 10:15:37.658302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '506a8746ca18'
down_revision = '5202b9f66f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('athlete', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('athlete', 'firstname',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.alter_column('athlete', 'surname',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('athlete', 'surname',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    op.alter_column('athlete', 'firstname',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    op.alter_column('athlete', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
