"""empty message

Revision ID: 61fb7c52c1ab
Revises: 4d5b0d5e8a74
Create Date: 2018-06-15 00:57:29.583194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61fb7c52c1ab'
down_revision = '4d5b0d5e8a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stadium_name', sa.String(length=30), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('olympic_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stadium_olympic_year'), 'stadium', ['olympic_year'], unique=False)
    op.create_index(op.f('ix_stadium_stadium_name'), 'stadium', ['stadium_name'], unique=False)
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olympic_year', sa.Integer(), nullable=True),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=False),
    sa.Column('sport_event_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['sport_event_id'], ['sport.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadium.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_olympic_year'), 'result', ['olympic_year'], unique=False)
    op.create_index(op.f('ix_result_position'), 'result', ['position'], unique=False)
    op.create_table('stadium_sport_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=False),
    sa.Column('sport_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sport_event_id'], ['sport.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadium.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stadium_sport_event')
    op.drop_index(op.f('ix_result_position'), table_name='result')
    op.drop_index(op.f('ix_result_olympic_year'), table_name='result')
    op.drop_table('result')
    op.drop_index(op.f('ix_stadium_stadium_name'), table_name='stadium')
    op.drop_index(op.f('ix_stadium_olympic_year'), table_name='stadium')
    op.drop_table('stadium')
    # ### end Alembic commands ###
