"""empty message

Revision ID: 717fab9af4ba
Revises: f5e577ad5999
Create Date: 2018-06-14 08:10:53.916838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717fab9af4ba'
down_revision = 'f5e577ad5999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport_event', sa.Column('sport_category', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_sport_event_sport_category'), 'sport_event', ['sport_category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sport_event_sport_category'), table_name='sport_event')
    op.drop_column('sport_event', 'sport_category')
    # ### end Alembic commands ###
