"""empty message

Revision ID: 7f13dbe72a3f
Revises: 717fab9af4ba
Create Date: 2018-06-14 09:35:20.514991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f13dbe72a3f'
down_revision = '717fab9af4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_olympic_year_year', table_name='olympic_year')
    op.drop_table('olympic_year')
    op.add_column('athlete', sa.Column('olympic_year', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_athlete_olympic_year'), 'athlete', ['olympic_year'], unique=False)
    op.add_column('sport_event', sa.Column('olympic_year', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_sport_event_olympic_year'), 'sport_event', ['olympic_year'], unique=False)
    op.add_column('stadium', sa.Column('olympic_year', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_stadium_olympic_year'), 'stadium', ['olympic_year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stadium_olympic_year'), table_name='stadium')
    op.drop_column('stadium', 'olympic_year')
    op.drop_index(op.f('ix_sport_event_olympic_year'), table_name='sport_event')
    op.drop_column('sport_event', 'olympic_year')
    op.drop_index(op.f('ix_athlete_olympic_year'), table_name='athlete')
    op.drop_column('athlete', 'olympic_year')
    op.create_table('olympic_year',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('participating_country_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['participating_country_id'], [u'country.id'], name=u'olympic_year_participating_country_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'olympic_year_pkey')
    )
    op.create_index('ix_olympic_year_year', 'olympic_year', ['year'], unique=False)
    # ### end Alembic commands ###
