"""empty message

Revision ID: 95d9531687dd
Revises: 357652fef1eb
Create Date: 2018-06-14 10:42:38.971268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d9531687dd'
down_revision = '357652fef1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olympic_year', sa.DateTime(), nullable=True),
    sa.Column('country_name', sa.String(length=30), nullable=False),
    sa.Column('geolocation', sa.String(length=30), nullable=False),
    sa.Column('climate', sa.String(length=20), nullable=False),
    sa.Column('continent', sa.String(length=20), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('num_of_states', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_country_name'), 'country', ['country_name'], unique=False)
    op.create_index(op.f('ix_country_olympic_year'), 'country', ['olympic_year'], unique=False)
    op.create_table('sport_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_category', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sport_category_sport_category'), 'sport_category', ['sport_category'], unique=False)
    op.create_table('stadium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stadium_name', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('olympic_year', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stadium_olympic_year'), 'stadium', ['olympic_year'], unique=False)
    op.create_index(op.f('ix_stadium_stadium_name'), 'stadium', ['stadium_name'], unique=False)
    op.create_table('athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olympic_year', sa.DateTime(), nullable=True),
    sa.Column('firstname', sa.String(length=25), nullable=False),
    sa.Column('surname', sa.String(length=25), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_email'), 'athlete', ['email'], unique=True)
    op.create_index(op.f('ix_athlete_firstname'), 'athlete', ['firstname'], unique=False)
    op.create_index(op.f('ix_athlete_olympic_year'), 'athlete', ['olympic_year'], unique=False)
    op.create_index(op.f('ix_athlete_surname'), 'athlete', ['surname'], unique=False)
    op.create_table('sport_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_category_id', sa.Integer(), nullable=False),
    sa.Column('sport_event', sa.String(length=30), nullable=False),
    sa.Column('olympic_year', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sport_category_id'], ['sport_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sport_event_olympic_year'), 'sport_event', ['olympic_year'], unique=False)
    op.create_index(op.f('ix_sport_event_sport_event'), 'sport_event', ['sport_event'], unique=False)
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('sport_event_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['sport_event_id'], ['sport_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_position'), 'result', ['position'], unique=False)
    op.create_table('stadium_sport_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=False),
    sa.Column('sport_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sport_event_id'], ['sport_event.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadium.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stadium_sport_event')
    op.drop_index(op.f('ix_result_position'), table_name='result')
    op.drop_table('result')
    op.drop_index(op.f('ix_sport_event_sport_event'), table_name='sport_event')
    op.drop_index(op.f('ix_sport_event_olympic_year'), table_name='sport_event')
    op.drop_table('sport_event')
    op.drop_index(op.f('ix_athlete_surname'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_olympic_year'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_firstname'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_email'), table_name='athlete')
    op.drop_table('athlete')
    op.drop_index(op.f('ix_stadium_stadium_name'), table_name='stadium')
    op.drop_index(op.f('ix_stadium_olympic_year'), table_name='stadium')
    op.drop_table('stadium')
    op.drop_index(op.f('ix_sport_category_sport_category'), table_name='sport_category')
    op.drop_table('sport_category')
    op.drop_index(op.f('ix_country_olympic_year'), table_name='country')
    op.drop_index(op.f('ix_country_country_name'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
