"""empty message

Revision ID: a5c02df4a12a
Revises: e054dc086c16
Create Date: 2018-06-14 21:45:52.434856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c02df4a12a'
down_revision = 'e054dc086c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('olympic_year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_result_olympic_year'), 'result', ['olympic_year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_olympic_year'), table_name='result')
    op.drop_column('result', 'olympic_year')
    # ### end Alembic commands ###
