"""empty message

Revision ID: c60c05b88d77
Revises: 17c3eb1e6a2e
Create Date: 2018-06-14 10:11:14.154235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60c05b88d77'
down_revision = '17c3eb1e6a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_result_position'), 'result', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_position'), table_name='result')
    # ### end Alembic commands ###
