"""empty message

Revision ID: ce571f6b0f9e
Revises: 22eca6dee2ce
Create Date: 2018-06-01 10:54:23.492554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce571f6b0f9e'
down_revision = '22eca6dee2ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('num_of_states', sa.Integer(), nullable=True))
    op.add_column('country', sa.Column('population', sa.Integer(), nullable=True))
    op.add_column('country', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'size')
    op.drop_column('country', 'population')
    op.drop_column('country', 'num_of_states')
    # ### end Alembic commands ###
