"""empty message

Revision ID: e054dc086c16
Revises: 76aa1a5ff429
Create Date: 2018-06-14 21:43:32.876421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e054dc086c16'
down_revision = '76aa1a5ff429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olympic_year', sa.Integer(), nullable=True),
    sa.Column('country_name', sa.String(length=30), nullable=False),
    sa.Column('geolocation', sa.String(length=30), nullable=False),
    sa.Column('climate', sa.String(length=20), nullable=False),
    sa.Column('continent', sa.String(length=20), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('num_of_states', sa.Integer(), nullable=False),
    sa.Column('president', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_country_name'), 'country', ['country_name'], unique=False)
    op.create_index(op.f('ix_country_olympic_year'), 'country', ['olympic_year'], unique=False)
    op.create_table('sport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_category', sa.String(length=30), nullable=False),
    sa.Column('sport_event', sa.String(length=30), nullable=False),
    sa.Column('olympic_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sport_olympic_year'), 'sport', ['olympic_year'], unique=False)
    op.create_index(op.f('ix_sport_sport_category'), 'sport', ['sport_category'], unique=False)
    op.create_index(op.f('ix_sport_sport_event'), 'sport', ['sport_event'], unique=False)
    op.create_table('athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olympic_year', sa.Integer(), nullable=True),
    sa.Column('firstname', sa.String(length=25), nullable=False),
    sa.Column('surname', sa.String(length=25), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('athlete_picture_url', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_email'), 'athlete', ['email'], unique=True)
    op.create_index(op.f('ix_athlete_firstname'), 'athlete', ['firstname'], unique=False)
    op.create_index(op.f('ix_athlete_olympic_year'), 'athlete', ['olympic_year'], unique=False)
    op.create_index(op.f('ix_athlete_surname'), 'athlete', ['surname'], unique=False)
    op.create_table('stadium_sport_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=False),
    sa.Column('sport_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sport_event_id'], ['sport.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadium.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=False),
    sa.Column('sport_event_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['sport_event_id'], ['sport.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadium.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_position'), 'result', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_position'), table_name='result')
    op.drop_table('result')
    op.drop_table('stadium_sport_event')
    op.drop_index(op.f('ix_athlete_surname'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_olympic_year'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_firstname'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_email'), table_name='athlete')
    op.drop_table('athlete')
    op.drop_index(op.f('ix_sport_sport_event'), table_name='sport')
    op.drop_index(op.f('ix_sport_sport_category'), table_name='sport')
    op.drop_index(op.f('ix_sport_olympic_year'), table_name='sport')
    op.drop_table('sport')
    op.drop_index(op.f('ix_country_olympic_year'), table_name='country')
    op.drop_index(op.f('ix_country_country_name'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
