"""empty message

Revision ID: e47903c7a51d
Revises: 95d9531687dd
Create Date: 2018-06-14 19:56:25.859512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47903c7a51d'
down_revision = '95d9531687dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athlete', sa.Column('athlete_picture_url', sa.String(length=50), nullable=True))
    op.add_column('country', sa.Column('president', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'president')
    op.drop_column('athlete', 'athlete_picture_url')
    # ### end Alembic commands ###
