"""empty message

Revision ID: f4a6d1980918
Revises: ce571f6b0f9e
Create Date: 2018-06-01 11:54:10.193308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a6d1980918'
down_revision = 'ce571f6b0f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('olympic_year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.DateTime(), nullable=True),
    sa.Column('participating_country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participating_country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_olympic_year_year'), 'olympic_year', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_olympic_year_year'), table_name='olympic_year')
    op.drop_table('olympic_year')
    # ### end Alembic commands ###
